#+STARTUP: latexpreview
* Bisectors of segments
** There are 2 line segments from $(x_1,y_1)$ to $(x_2,y_2)$ and from $(x_2,y_2)$ to $(x_3,y_3)$ called $S_1$ and $S_2$ respectively. Parallel to these are segments $S_{1A}$, $S_{1B}$ (both parallel to $S_1$) and $S_{2A}$ and $S_{2B}$ (both parallel to $S_2$) where the perpendicular distance from all points on each of these segments to their respective parallel segment $S_1$ or $S_2$ is $d$.
** The slopes of $S_1$ and $S_2$ are defined as:
\begin{align*}
m_1 &= \frac{y_2-y_1}{x_2-x_1} \\
m_2 &= \frac{y_3-y_2}{x_3-x_2} \\
\end{align*}
** The equations of $S_{1A}$ and $S_{2A}$ (the segments to the same side of $S_1$ and $S_2$) are defined below. The equations of $S_{1B}$ and $S_{2B}$ are defined similarly but we won't elaborate further on these.
\begin{align*}
y &= m_1 \times x +c_1 \\
y &= m_2 \times x +c_2
\end{align*}
*** TODO Identify which segment is on the same side as the other of the 2 original segments
** We wish to identify where $S_{1A}$ and $S_{2A}$ intersect. Therefore the 2 $y$ s (and obviously $x$ s as well) are identifcal to each other:
\begin{align*}
\implies m_1 \times x +c_1 &=m_2 \times x +c_2 \\
\implies c_1 - c_2 &= m_2 \times x - m_1 \times x \\
\implies c_1 - c_2 &= x(m_2 - m_1) \\
\implies x &= \frac{c_1-c_2}{m_2-m_1} \\
\end{align*}
** Next calculate $c_1$ and $c_2$ using $m_1$, $m_2$ and the known width of the stroke. 
*** Original broken method
**** Returning to our original line segments, consider first the line that passes through $(x_1, y_1)$ itself.
 \begin{align*}
 y &= m_1 \times x + c_1 \\
 \implies y_1 &= m_1 \times x_1 + c_1 \\
 \implies c_1 &= m_1 \times x_1 - y_1 \\
 \implies c_1 &= \frac{y_2-y_1}{x_2-x_1} \times x_1 - y_1 \\
 \end{align*}
***** There's a mistake in the derivation of $c_1$ above
**** Next generalise and calculate $c_{1x}$ for any line with the slope $m_1$. Assume stroke width is $w$.
 \begin{align*}
 c_{1x} &= c_1 + \frac{y_2-y_1}{x_2-x_1} \times x_1 - y_1 \\
 \end{align*}
*** 2nd broken attempt
**** see c1x_boundary.svg
*** 3rd attempt
**** Assume we know the equation for the first segment that is parallel to $S_1$ and a distance of $d$ from it.
***** $y=
** Deriving quad vertices
\begin{align*}
{v3}_y &= {fd_signed}_{grad}{v3}_x+c
\end{align*}

* Brush size progress bar
** nomenclature
*** $\mathit{MP}$ is MAX_PROGRESS in the source, 200 currently 
*** $\mathit{HS}$ is HALF_SIZE, 30 currently
*** $s$ is size, currently ranges from 0 to $\mathit{ms}$, should range from 1 to $\mathit{ms}$
*** $p$ is pProg, ranges from 0 to $\mathit{MP}-1$
*** $\mathit{ms}$ is largest brush size
*** $\mathit{hs}=$ if $\mathit{HS}<\mathit{ms}$
**** $\mathit{HS}$
*** else
**** $\frac{\mathit{ms}}{2}$
*** $\mathit{ohm}=\mathit{ms}-\mathit{hs}$
** progress to size
*** Results
| p    | s                                          |
|------+--------------------------------------------|
| 0    | 0                                          |
| MP-1 | 0.3+0.99ms (HS<ms) or (1.99*ms)/2 (HS>=ms) |
|      |                                            |

*** if $p<\frac{\mathit{MP}}{2}$
**** $s=\frac{p \times \mathit{hs}}{\frac{\mathit{MP}}{2}}$
***** Examples
****** if $p=0$
******* $s=\frac{0 \times \mathit{hs}}{\frac{\mathit{MP}}{2}}=0$
****** if $p=\mathit{MP}-1$, can only happen if $\mathit{MP}<2$ which it isn't currently
*******
\begin{align*}
s&= \frac{(\mathit{MP}-1) \times \mathit{hs}}{\frac{\mathit{MP}}{2}} \\ 
 &= \frac{2 \times (\mathit{MP}-1) \times \mathit{hs}}{\mathit{MP}} \\
 &= \frac{2 \times \mathit{MP} \times \mathit{hs} - 2 \times \mathit{hs}}{\mathit{MP}} \\
 &= 2 \times \mathit{hs} - \frac{2 \times \mathit{hs}}{MP} \\
 &= 59.7 \enspace \mathtt{or} \enspace \frac{199 \times \mathit{ms}}{200}\\
\end{align*}
*** else
****  
\begin{align*}
s &= \mathit{hs}+\frac{p-\frac{\mathit{MP}}{2}}{\mathit{hp}} \times \mathit{ohm} \\
&= \mathit{hs}+\frac{p-\frac{\mathit{MP}}{2}}{\frac{\mathit{MP}}{2}} \times (\mathit{ms}-\mathit{hs}) \\
&= \mathit{hs}+(\frac{p}{\frac{\mathit{MP}}{2}}-1) \times (\mathit{ms}-\mathit{hs}) \\
&= \mathit{hs}+(2 \frac{p}{\mathit{MP}}-1) \times (\mathit{ms}-\mathit{hs}) \\
\end{align*}
***** where $\mathit{HS}<\mathit{ms}$, affects so $\mathit{hs}=\mathit{HS}$
****** 
\begin{align*}
s &= \mathit{hs}+(2 \frac{p}{\mathit{MP}}-1) \times (\mathit{ms}-\mathit{hs}) \\
  &= \mathit{HS}+(2 \frac{p}{\mathit{MP}}-1) \times (\mathit{ms}-\mathit{HS}) \\
\end{align*}
******* Examples
******** if $p=0$, can only happen if $MP \leq 0$, contradiction
******** if $p=\mathit{MP}-1$
********* 
\begin{align*}
s &= \mathit{HS}+(2 \frac{p}{\mathit{MP}}-1) \times (\mathit{ms}-\mathit{HS}) \\
  &= 30 + (2 \times \frac{200-1}{200}-1) \times (\mathit{ms} - 30) \\
  &= 30 + 0.99 \times (\mathit{ms} - 30) \\
  &= 0.3 + 0.99 \times \mathit{ms} \\
\end{align*}

***** otherwise (i.e. $\mathit{HS} \ge \mathit{ms}$) so $\mathit{hs}=\frac{\mathit{ms}}{2}$
****** 
\begin{align*}
s &= \mathit{hs}+(2 \frac{p}{\mathit{MP}}-1) \times (\mathit{ms}-\mathit{hs}) \\
&= \frac{\mathit{ms}}{2}+(2 \frac{p}{\mathit{MP}}-1) \times (\mathit{ms}-\frac{\mathit{ms}}{2}) \\
\end{align*}
******* Examples
******** if $p=0$, can only happen if $MP \leq 0$
******** if $p=\mathit{MP}-1$
********* 
\begin{align*}
s &= \frac{\mathit{ms}}{2}+(2 \frac{p}{\mathit{MP}}-1) \times (\mathit{ms}-\frac{\mathit{ms}}{2}) \\
  &= \frac{\mathit{ms}}{2}+(2 \frac{\mathit{MP}-1}{\mathit{MP}}-1) \times (\mathit{ms}-\frac{\mathit{ms}}{2}) \\
  &= \frac{\mathit{ms}}{2}+(2 \frac{\mathit{MP}-1}{\mathit{MP}}-1) \times \frac{\mathit{ms}}{2} \\
  &= \frac{\mathit{ms}}{2}+\frac{\mathit{MP}-2}{2 \times \mathit{MP}} \times \mathit{ms} \\
  &= \frac{\mathit{ms} \times \mathit{MP}}{2 \times \mathit{MP}}+\frac{\mathit{ms} \times (\mathit{MP}-2)}{2 \times \mathit{MP}} \\
  &= \frac{\mathit{ms} \times \mathit{MP} + \mathit{ms} \times (\mathit{MP}-2)}{2 \times \mathit{MP}} \\
  &= \frac{\mathit{ms} \times (2 \times \mathit{MP}-2)}{2 \times \mathit{MP}} \\
  &= \frac{1.99 \times \mathit{ms}}{2} \\
\end{align*}
** size to progress
*** Results
|----------------------+----|
| s                    | p  |
|----------------------+----|
| 0                    | 0  |
| ms                   | MP |
| (1.99*ms)/2 (HS>=ms) |    |
| 0.3+0.99ms (HS<ms)   |    |

*** if $s>\mathit{ms}$
**** $p=\mathit{MP}-1$
***** Examples
****** $s=0$, can only be possible if ms is -ve. Safe to say this is impossible
****** $s=\mathit{ms}$, contradiction
*** else if $s<\mathit{hs}$
**** $p=\frac{s \times \frac{\mathit{MP}}{2}}{\mathit{HS}}$
***** Examples
****** $s=0$
******* 
\begin{align*}
p &= \frac{s \times \frac{\mathit{MP}}{2}}{\mathit{HS}} \\
  &= \frac{0 \times \frac{\mathit{MP}}{2}}{\mathit{HS}} \\
  &= 0 
\end{align*}
****** $s=\mathit{ms}$, contradiction ($s<\mathit{hs} \implies \mathit{ms}<\mathit{hs} \implies \mathit{hs} \ge \mathit{ms}$) but $\mathit{ms}<\mathit{hs} \implies \mathit{HS}<\mathit{ms} \land \mathit{hs}=\mathit{HS} \lor \mathit{HS} \ge \mathit{ms} \land \mathit{hs}=\frac{\mathit{ms}}{2}$ and neither of these 2 clauses can be true.
*** else
**** $p=\frac{\mathit{MP}}{2}+\frac{s-\mathit{hs}}{\mathit{ohm}} \times \frac{\mathit{MP}}{2}$
\begin{align*}
p&=\frac{\mathit{MP}}{2}+\frac{s-\mathit{hs}}{\mathit{ohm}} \times \frac{\mathit{MP}}{2}\\
&=\frac{\mathit{MP}}{2}+\frac{s-\mathit{hs}}{\mathit{ms}-\mathit{hs}} \times \frac{\mathit{MP}}{2}\\
&=\frac{\mathit{MP}}{2} \times (1 + \frac{s-\mathit{hs}}{\mathit{ms}-\mathit{hs}})\\
\end{align*}
***** where $\mathit{HS}<\mathit{ms}$
****** 
\begin{align*}
p&=\frac{\mathit{MP}}{2} \times (1 + \frac{s-\mathit{hs}}{\mathit{ms}-\mathit{hs}})\\
&=\frac{\mathit{MP}}{2} \times (1 + \frac{s-\mathit{HS}}{\mathit{ms}-\mathit{HS}})\\
\end{align*}
******* Examples
****** $s=0$, can only possible if $\mathit{ms}$ is -ve. Safe to say this is impossible
****** $s=\mathit{ms}$
******* 
\begin{align*}
p &= \frac{\mathit{MP}}{2} \times (1 + \frac{s-\mathit{HS}}{\mathit{ms}-\mathit{HS}}) \\
  &= \frac{\mathit{MP}}{2} \times (1 + \frac{\mathit{ms}-\mathit{HS}}{\mathit{ms}-\mathit{HS}}) \\
  &= \mathit{MP}
\end{align*}
***** otherwise
****** 
\begin{align*}
p&=\frac{\mathit{MP}}{2} \times (1 + \frac{s-\mathit{hs}}{\mathit{ms}-\mathit{hs}})\\
&=\frac{\mathit{MP}}{2} \times (1 + \frac{s-\frac{\mathit{ms}}{2}}{\mathit{ms}-\frac{\mathit{ms}}{2}})\\
\end{align*}
******* Examples
******** $s=0$, contraction given that $\mathit{HS} \ge 0$: $s \ge \mathit{hs} \implies 0 \ge \mathit{hs} \iff \mathit{ms} \le 0$
******** $s=\mathit{ms}$
********* 
\begin{align*}
p &=\frac{\mathit{MP}}{2} \times (1 + \frac{s-\frac{\mathit{ms}}{2}}{\mathit{ms}-\frac{\mathit{ms}}{2}})\\
  &=\frac{\mathit{MP}}{2} \times (1 + \frac{\mathit{ms}-\frac{\mathit{ms}}{2}}{\mathit{ms}-\frac{\mathit{ms}}{2}})\\
  &= \mathit{MP}
\end{align*}

